### ISSUE TITLE
PHP 7 not recognised 

### ISSUE THREAD

**Issue by NielsLeenheer** [sindresorhus/find-versions#4]
PHP 7 is recognised as `3.0.0-dev`, instead of `7.0.0-rc.6`

````
$ php --version
PHP 7.0.0RC6 (cli) (built: Oct 29 2015 13:46:05) ( NTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0-dev, Copyright (c) 1998-2015 Zend Technologies
````

This currently breaks grunt-php when PHP 7 is installed, because it has a requirement of `>=5.4`

**Comment by sindresorhus** [comment]
I assume you meant to open this on `bin-version` instead. Added a test to prove it works correctly: https://github.com/sindresorhus/bin-version/commit/2a45ac9a40d5cfcfb9e313d5b7a9208d499d663d
